### PR TITLE
Tags Display In Dropdowns

### PR DESCRIPTION
**Pull request by danelegassick**
Tags for region and context are updated based on when the box is checked, then filtered for duplicates

a each loop is ran for all of the tags selected, this is styled inline and wraps when there are many selected

regions updated to have flag emojis in text, as that is how every listing of text is displayed in prototype

### CODE REVIEW

**Comment by alexisraya** [comment]
@danelegassick Im holding off from pushing for now because the heights shift when you select a region or context and it looks weird

**Comment by alexisraya** [comment]
ensure that the emojis are compatible for al major browsers

**Comment by danelegassick** [comment]
> @danelegassick Im holding off from pushing for now because the heights shift when you select a region or context and it looks weird

do you mean when it flex wraps? how should i handle that?

**Comment by danelegassick** [comment]
> ensure that the emojis are compatible for al major browsers

I tested on Opera, Firefox, Chrome, and Safari (and it works!) , but i havent been able to test on other operating systems like android

**Pull request merged**
